### ISSUE TITLE
Invalid YAML loading a rule with a multiline field

### ISSUE THREAD

**Issue by vitovitolo** [grafana/cortex-tools#102]
## How to reproduce?

- port-forward ruler Pod 
```
$ kubectl -n cortex port-forward deploy/ruler 8080:80
```

- create a rule group YAML file with multiline in `expr` field, with a breaking line at the beginning 
```
$ cat >> test.yml << EOF
groups:
  - name: rule-group-name
    rules:
    - alert: alert-name
      expr: |

        up{jop="my-awesome-job"} == 0
EOF
```

- load rule
``` 
$ cortextool rules load --address "http://localhost:8080" --id=0 --log.level="debug" test.yml
```

- cortextool debug output:
```
INFO[0000] log level set to debug
DEBU[0000] path built to request rule group              url=/api/prom/rules/test/rule-group-name
DEBU[0000] sending request to cortex api                 method=GET url="http://localhost:8080/api/prom/rules/test/rule-group-name"
DEBU[0000] checking response                             status="404 Not Found"
DEBU[0000] resource not found                            fields.msg="request failed with response body group does not exist\n" status="404 Not Found"
DEBU[0000] sending request to cortex api                 method=POST url="http://localhost:8080/api/prom/rules/test"
DEBU[0000] checking response                             status="400 Bad Request"
ERRO[0000] requests failed                               fields.msg="request failed with response body unable to decoded rule group\n" status="400 Bad Request"
ERRO[0000] unable to load rule group                     error="failed request to the cortex api" group=rule-group-name namespace=test
cortextool: error: load operation unsuccessful, try --help
```

## additional data

- cortex ruler version 1.4.0
- cortex-tools compiled with current master HEAD https://github.com/grafana/cortex-tools/commit/432ad779ae0f28552ffe7f1f0d6ddd3c32b52210

- http request dump 
```
POST /api/prom/rules/test HTTP/1.1
Host: localhost:8080
User-Agent: Go-http-client/1.1
Content-Length: 107
X-Scope-Orgid: 0
Accept-Encoding: gzip

name: rule-group-name
rules:
    - alert: alert-name
      expr: |4

        up{jop="my-awesome-job"} == 0
```

As you can see, the body content is not a valid YAML.

# expected behaviour

cortex-tools should ensure is sending a valid YAML before reach cortex API.

I'm willing to help to fix it with some help.

Thanks!
