### ISSUE TITLE
YAML format of `rules get` should match `rules sync`

### ISSUE THREAD

**Issue by lukebigum** [grafana/cortex-tools#137]
It would be helpful if the output format of `cortextool rules get <namespace> <group>` matched the exact format expected to `cortextool rules sync`.  This would make it easier to `get` down all rules and commit them into Git, then `sync` them back again.  Right now I have to munge the YAML slightly to make it compatible to `sync`.

Right now the format is this:

```
$ cortextool rules get somenamespace anygroup
name: anygroup
rules:
    - alert: FrontEnd Prometheus
      expr: .......
```

Ideally it would be this:

```
namespace: somenamespace
groups:
    - name: anygroup
      rules:
        - alert: FrontEnd Prometheus
          expr: ........
```
