### ISSUE TITLE
[BUG] `cortextool alertmanager get` does not output valid YAML

### ISSUE THREAD

**Issue by justinTM** [grafana/cortex-tools#263]
Steps to reproduce:
```console
$ cortextool alertmanager get | yq .
Error: bad file '-': yaml: control characters are not allowed
```

**Comment by justinTM** [comment]
Figured it out. the command outputs a "Template:" declaration which is empty, causing YAML syntax error. Will open a PR soon.

```yaml
# example bad YAML
global:
  victorops_api_key: XXXXXXXXXXXXXXXX
  smtp_from: grafana@my-employer.grafana.net
  smtp_smarthost: smtprelay:2525
  smtp_require_tls: false

route:
  group_by: ["..."]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: my-receiver

  routes:
    ...
Templates:
```
